[workspace]
members = [
    ".",
]

[package]
name = "cph"
version = "0.1.0"
edition = "2021"
authors = ["sugipamo"]
license = "MIT"
description = "競技プログラミングの問題を解くためのCLIツール"
repository = "https://github.com/sugipamo/project-cph"
readme = "README.md"
keywords = ["competitive-programming", "cli", "atcoder", "contest", "helper"]
categories = ["command-line-utilities", "development-tools"]

[[bin]]
name = "cph"
path = "src/bin/cph.rs"

[[bin]]
name = "a"
path = "workspace/a.rs"

[[bin]]
name = "a_gen"
path = "workspace/a_gen.rs"

[[bin]]
name = "b"
path = "workspace/b.rs"

[[bin]]
name = "b_gen"
path = "workspace/b_gen.rs"

[[bin]]
name = "c"
path = "workspace/c.rs"

[[bin]]
name = "c_gen"
path = "workspace/c_gen.rs"

[[bin]]
name = "d"
path = "workspace/d.rs"

[[bin]]
name = "d_gen"
path = "workspace/d_gen.rs"

[[bin]]
name = "e"
path = "workspace/e.rs"

[[bin]]
name = "e_gen"
path = "workspace/e_gen.rs"

[[bin]]
name = "f"
path = "workspace/f.rs"

[[bin]]
name = "f_gen"
path = "workspace/f_gen.rs"

[[bin]]
name = "g"
path = "workspace/g.rs"

[[bin]]
name = "g_gen"
path = "workspace/g_gen.rs"

[dependencies]
clap = { version = "4.5.1", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
thiserror = "1.0"
once_cell = "1.0"
tempfile = "3.8"
open = "5.0"
rpassword = "7.3"
chrono = "0.4"
dirs = "5.0"
colored = "2.0"
proconio = "0.4"

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.0"
tempfile = "3.8"

[lib]
name = "cph"
path = "src/lib.rs"
