[workspace]
members = [
    ".",
    "workspace/compile/rust"
]

[package]
name = "cph"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "cph"
path = "src/bin/cph.rs"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
anyhow = "1.0"
tokio = { version = "1.35", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
thiserror = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
once_cell = "1.19"
tempfile = "3.8"

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.0"
tempfile = "3.8"
