[workspace]
members = [
    ".",
    "compile/rust",
]

[package]
name = "cph"
version = "0.1.0"
edition = "2021"
authors = ["sugipamo"]
license = "MIT"
description = "競技プログラミングの問題を解くためのCLIツール"
repository = "https://github.com/sugipamo/project-cph"
readme = "README.md"
keywords = ["competitive-programming", "cli", "atcoder", "contest", "helper"]
categories = ["command-line-utilities", "development-tools"]

[[bin]]
name = "cph"
path = "src/bin/cph.rs"

[features]
default = []
docker_test = []

[dependencies]
clap = { version = "4.5.1", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
thiserror = "1.0"
once_cell = "1.0"
tempfile = "3.8"
open = "5.0"
rpassword = "7.3"
chrono = "0.4"
dirs = "5.0"
colored = "2.0"
proconio = "0.4"
bollard = "0.15"
async-trait = "0.1"
futures = "0.3"

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.0"
tempfile = "3.8"
tokio-test = "0.4"

[lib]
name = "cph"
path = "src/lib.rs"
