# 必ずanyhow::Errorのみを使用する
disallowed-types = [
    "std::error::Error",
    "std::io::Error",
    "Box<dyn std::error::Error>",
    "std::prelude",
    "Box<dyn std::error::Error + Send + Sync>",
    "lazy_static::lazy_static"
]

# ファイルを分割することでAIが存在を認識できず、重複したコードが生成されるため禁止
disallowed-names = [
    "type.rs",
    "types.rs",
    "prelude.rs",
    "constants.rs",
    "const.rs",
    "consts.rs",
    "utils.rs",
    "helpers.rs",
    "common.rs",
    "models.rs",
    "errors.rs",
    "error.rs",
    "traits.rs"
]

# 複雑性の制限
too-many-arguments-threshold = 6
too-many-lines-threshold = 300

# 命名規則
type-complexity-threshold = 250

# パフォーマンス関連
vec-box-size-threshold = 0

# その他の制限
cognitive-complexity-threshold = 25