# Clippy configuration file

# Maximum cognitive complexity allowed
cognitive-complexity-threshold = 30

# Maximum number of lines allowed in a function
too-many-lines-threshold = 100

# Maximum number of arguments allowed in a function
too-many-arguments-threshold = 7

# Minimum length for string literals to be suspicious
trivial-copy-size-limit = 40

# Maximum size of types passed by value
pass-by-value-size-limit = 256

# Maximum allowed cyclomatic complexity
# Note: cyclomatic-complexity-threshold is deprecated, use cognitive-complexity-threshold instead

# Whether to warn on TODOs
# Note: warn-on-todo is not a valid clippy configuration field

# Maximum allowed nesting level
excessive-nesting-threshold = 5

# Disallowed names
disallowed-names = ["foo", "bar", "baz", "tmp", "temp", "test"]

# Allow certain macros
allowed-duplicate-crates = []

# Enable extra restriction lints
avoid-breaking-exported-api = true

# Allow dbg! in tests
allow-dbg-in-tests = true

# Enforce MSRV
msrv = "1.70.0"