[package]
name = "solution"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
name = "main"
path = "src/main.rs"

[dependencies]
proconio = "0.4"  # 競プロでよく使用される入力ライブラリ
num = "0.4"       # 数値計算用ライブラリ
itertools = "0.12" # イテレータ拡張ライブラリ
solution = { path = "." }  # 自身への参照（lib.rsの機能を使用可能に） 