# 言語のエイリアス
languages:
  python:
    - Python
    - python3
  pypy:
    - py
    - PyPy
    - pypy3
    - PyPy3
  cpp:
    - c++
    - C++
    - Cpp
  rust:
    - Rust
    - rs

# コマンドのエイリアス
commands:
  test:
    - t
    - check
  open:
    - o
    - show
  submit:
    - s
    - sub
  init:
    - i
    - create
  language:
    - l
    - lang
  login:
    - auth

# サイトのエイリアス
sites:
  atcoder:
    - at-coder
    - at_coder
    - AtCoder
    - ac 