parameter_types:
  - name: test
    pattern: "test"
    config_key: "test"
  - name: submit
    pattern: "submit"
    config_key: "submit"
  - name: site_id
    pattern: "site"
    config_key: "sites"
  - name: language
    pattern: "language"
    config_key: "languages"
  - name: contest
    pattern: "contest_id"
  - name: problem
    pattern: "problem_id"

ordered:
  - ["site_id", "command", "problem_id"]
  - ["command", "problem_id"]
  - ["site_id", "command", "problem_id", "language"]
  - ["command", "problem_id", "language"]
  - ["site_id", "command", "contest_id"]
  - ["command", "contest_id"]
  - ["site_id", "command"]
  - ["command"]
  - ["command", "language"]

unordered:
  - ["site_id", "contest_id", "command", "problem_id"]
  - ["contest_id", "command", "problem_id"]
  - ["command", "contest_id", "problem_id"]
  - ["site_id", "contest_id", "command", "problem_id", "language"]
  - ["contest_id", "command", "problem_id", "language"]
  - ["command", "contest_id", "problem_id", "language"]
  - ["command", "contest_id"]