parameter_types:
  - name: command
    pattern: "command"
  - name: site
    pattern: "site_id"
    config_key: "sites"
  - name: language
    pattern: "language"
    config_key: "languages"
  - name: contest
    pattern: "contest_id"
  - name: problem
    pattern: "problem_id"

commands:
  test:
    aliases: ["test", "t", "check"]
    ordered:
      - ["site_id", "command", "problem_id"]
      - ["command", "problem_id"]
    unordered:
      - ["site_id", "contest_id", "command", "problem_id"]
      - ["contest_id", "command", "problem_id"]
      - ["command", "contest_id", "problem_id"]
  open:
    aliases: ["open", "o", "show"]
    ordered:
      - ["site_id", "command", "problem_id"]
      - ["command", "problem_id"]
    unordered:
      - ["site_id", "contest_id", "command", "problem_id"]
      - ["contest_id", "command", "problem_id"]
      - ["command", "contest_id", "problem_id"]
  submit:
    aliases: ["submit", "s", "sub"]
    ordered:
      - ["site_id", "command", "problem_id"]
      - ["command", "problem_id"]
    unordered:
      - ["site_id", "contest_id", "command", "problem_id"]
      - ["contest_id", "command", "problem_id"]
      - ["command", "contest_id", "problem_id"]

  init:
    aliases: ["init", "i", "create"]
    ordered:
      - ["site_id", "command", "contest_id"]
      - ["command", "contest_id"]
    unordered:
      - ["command", "contest_id"]

  language:
    aliases: ["language", "l", "lang"]
    ordered:
      - ["site_id", "command", "language"]
      - ["command", "language"]
    unordered:
      - ["command", "language"]

  login:
    aliases: ["login", "auth"]
    ordered:
      - ["site_id", "command"]
      - ["command"]