parameter_types:
  init:
    aliases: ["init", "i", "create"]
    execute: "init"
  login:
    aliases: ["login", "auth"]
    execute: "login"
  open:
    aliases: ["open", "o", "show"]
    execute: "open"
  test:
    aliases: ["test", "t", "check"]
    execute: "test"
  submit:
    aliases: ["submit", "s", "sub"]
    execute: "submit"
  language:
    rust:
      aliases: ["rs", "Rust", "RUST"]
    python:
      aliases: ["py", "python3"]
    pypy:
      aliases: ["pypy3", "PyPy", "PYPY"]
    cpp:
      aliases: ["c++", "gcc"]
  site:
    atcoder:
      aliases: ["ac", "at-coder", "at_coder", "AtCoder"]

ordered:
  - ["site_id", "command", "problem_id"]
  - ["command", "problem_id"]
  - ["site_id", "command", "problem_id", "language"]
  - ["command", "problem_id", "language"]
  - ["site_id", "command", "contest_id"]
  - ["command", "contest_id"]
  - ["site_id", "command"]
  - ["command"]
  - ["command", "language"]

unordered:
  - ["site_id", "contest_id", "command", "problem_id"]
  - ["contest_id", "command", "problem_id"]
  - ["command", "contest_id", "problem_id"]
  - ["site_id", "contest_id", "command", "problem_id", "language"]
  - ["contest_id", "command", "problem_id", "language"]
  - ["command", "contest_id", "problem_id", "language"]
  - ["command", "contest_id"]