# 基本設定（他の設定で継承される）
base:
  contest_dir:
    active: "active_contest"  # 現在の作業ディレクトリ
    storage: "contests"  # コンテスト保存ディレクトリ
    template: "contest_template"  # コンテストテンプレートディレクトリ
    compile: "compile"  # コンパイル用ディレクトリ

  sites:
    base:  # サイト共通の設定
      submit:
        wait: 0
        auto_yes: true
      test:
        directory: "test"
    atcoder:
      aliases: ["at-coder", "at_coder", "AtCoder", "ac"]
      url_pattern: "https://atcoder.jp/contests/{contest_id}/tasks/{problem_id}"

  docker:
    timeout_seconds: 5  # 実行タイムアウト（秒）
    memory_limit_mb: 128  # メモリ制限（MB）

  solution: "solution.{extension}"  # 解答ファイルのパターン
  generator: "generator.{extension}"  # ジェネレータファイルのパターン
  tester: "tester.{extension}"  # テスターファイルのパターン

# 言語設定（base の設定を継承）
rust:  # デフォルト言語
  aliases: ["Rust", "rs", "RUST"]
  extension: "rs"
  image: "rust:latest"
  compile: ["cargo", "build", "--release"]
  run: ["./target/release/main"]

python:
  aliases: ["Python", "py", "PYTHON"]
  extension: "py"
  image: "python:3.9-slim"
  run: ["python", "-u", "-c"]

pypy:
  aliases: ["PyPy", "py-py", "PYPY", "Pypy"]
  extension: "py"
  image: "pypy:3.9-slim"
  run: ["pypy3", "-u", "-c"]

cpp:
  aliases: ["C++", "cpp", "CPP"]
  extension: "cpp"
  image: "gcc:latest"
  compile: ["g++", "-std=c++17", "-O2", "main.cpp"]
  run: ["./a.out"]