# グステム全体の設定
system:
  contest_dir:
    active: "${CPH_ACTIVE_DIR-active_contest}"
    storage: "${CPH_STORAGE_DIR-archive}"
    template: "${CPH_TEMPLATE_DIR-contest_template}"
  
  compile_dir: "${CPH_COMPILE_DIR-compile/{name}}"

  docker:
    timeout_seconds: ${CPH_DOCKER_TIMEOUT-10}
    memory_limit_mb: ${CPH_DOCKER_MEMORY-256}

  source_file:
    solution: "${CPH_SOLUTION_FILE-main.{extension}}"
    generator: "${CPH_GENERATOR_FILE-gen.{extension}}"
    tester: "${CPH_TESTER_FILE-test.{extension}}"

  submit:
    wait: ${CPH_SUBMIT_WAIT-5}
    auto_yes: ${CPH_AUTO_YES-false}
  
  test:
    dir: "${CPH_TEST_DIR-cases}"

languages:
  # 言語の基本設定をアンカーとして定義
  _base: &lang_base
    compile: []
    run: []
    aliases: []

  rust:
    <<: *lang_base
    aliases: ["rs"]
    extension: "rs"
    image: "${CPH_RUST_IMAGE-rust:latest}"
    compile: ["rustc", "main.rs"]
    run: ["./main"]

  python:
    <<: *lang_base
    aliases: ["py", "python3"]
    extension: "py"
    image: "${CPH_PYTHON_IMAGE-python:3.11-slim}"
    run: ["python", "main.py"]

  pypy:
    <<: *lang_base
    aliases: ["pypy3"]
    extension: "py"
    image: "${CPH_PYPY_IMAGE-pypy:latest}"
    run: ["pypy3", "main.py"]

  cpp:
    <<: *lang_base
    aliases: ["c++", "gcc"]
    extension: "cpp"
    image: "${CPH_CPP_IMAGE-gcc:latest}"
    compile: ["g++", "-std=c++17", "-O2", "main.cpp"]
    run: ["./a.out"]

sites:
  # サイトの基本設定をアンカーとして定義
  _base: &site_base
    problem_url: ""
    submit_url: ""
    aliases: []
    submit: 
      wait: ${CPH_SUBMIT_WAIT-5}
      auto_yes: ${CPH_AUTO_YES-false}
    test:
      dir: "${CPH_TEST_DIR-cases}"

  atcoder:
    <<: *site_base
    aliases: ["ac"]
    problem_url: "https://atcoder.jp/contests/{contest_id}/tasks/{problem_id}"
    submit_url: "https://atcoder.jp/contests/{contest_id}/submit" 