# グステム全体の設定
system:
  browser: "${BROWSER-chrome}"
  editors:
    - "code"
    - "cursor"

  contest_dir:
    active: "${CPH_ACTIVE_DIR-active_contest}"
    storage: "${CPH_STORAGE_DIR-contest_archive}"
    template: "${CPH_TEMPLATE_DIR-contest_template}"
  
  active_contest_yaml: "${CPH_ACTIVE_CONTEST_YAML-active_contest.yaml}"

  compile_dir: "${CPH_COMPILE_DIR-compile/{name}}"

  docker:
    timeout_seconds: ${CPH_DOCKER_TIMEOUT-10}
    memory_limit_mb: ${CPH_DOCKER_MEMORY-256}
    mount_point: "/compile"

  templates:
    patterns:
      solution: "${CPH_SOLUTION_FILE-solution.{extension}}"
      generator: "${CPH_GENERATOR_FILE-generator.{extension}}"
      tester: "${CPH_TESTER_FILE-tester.{extension}}"
    directory: "${CPH_TEMPLATE_DIR-{name}}"

  submit:
    wait: ${CPH_SUBMIT_WAIT-5}
    auto_yes: ${CPH_AUTO_YES-false}
  
  test:
    dir: "${CPH_TEST_DIR-cases}"

# コマンドのエイリアス設定
commands:
  test:
    aliases: ["t", "check"]
  open:
    aliases: ["o", "show"]
  submit:
    aliases: ["s", "sub"]
  init:
    aliases: ["i", "create"]
  language:
    aliases: ["l", "lang"]
  login:
    aliases: ["auth"]

# 言語設定
languages:
  default: rust
  # 言語の基本設定をアンカーとして定義
  _base: &lang_base
    compile: []
    run: []
    aliases: []
    runner:
      needs_compilation: false
      require_files: []
      env_vars: []

  rust:
    <<: *lang_base
    aliases: ["rs", "Rust", "RUST"]
    extension: "rs"
    runner:
      image: "${CPH_RUST_IMAGE-rust:latest}"
      compile: ["rustc", "main.rs"]
      run: ["./main"]
      needs_compilation: true
      require_files: ["Cargo.toml"]
      env_vars:
        - "RUST_BACKTRACE=1"
    site_ids:
      _source: "online_judge_tool"
      _fallback:
        atcoder: "5054"  # Rust (rustc 1.70.0)

  python:
    <<: *lang_base
    aliases: ["py", "python3"]
    extension: "py"
    runner:
      image: "${CPH_PYTHON_IMAGE-python:3.11-slim}"
      run: ["python", "main.py"]
    site_ids:
      _source: "online_judge_tool"
      _fallback:
        atcoder: "4047"  # Python (CPython 3.11.4)

  pypy:
    <<: *lang_base
    aliases: ["pypy3", "PyPy", "PYPY"]
    extension: "py"
    runner:
      image: "${CPH_PYPY_IMAGE-pypy:latest}"
      run: ["pypy3", "main.py"]
    site_ids:
      _source: "online_judge_tool"
      _fallback:
        atcoder: "5078"  # Python (PyPy 3.10-v7.3.12)

  cpp:
    <<: *lang_base
    aliases: ["c++", "gcc"]
    extension: "cpp"
    runner:
      image: "${CPH_CPP_IMAGE-gcc:latest}"
      compile: ["g++", "-std=c++17", "-O2", "main.cpp"]
      run: ["./a.out"]
      needs_compilation: true
      env_vars:
        - "CPLUS_INCLUDE_PATH=/usr/include/c++/9"
    site_ids:
      _source: "online_judge_tool"
      _fallback:
        atcoder: "5001"  # C++ (GCC 9.2.1)

# サイト設定
sites:
  # サイトの基本設定をアンカーとして定義
  _base: &site_base
    problem_url: ""
    submit_url: ""
    aliases: []
    submit: 
      wait: ${CPH_SUBMIT_WAIT-5}
      auto_yes: ${CPH_AUTO_YES-false}
    test:
      dir: "${CPH_TEST_DIR-cases}"

  atcoder:
    <<: *site_base
    aliases: ["ac", "at-coder", "at_coder", "AtCoder"]
    problem_url: "https://atcoder.jp/contests/{contest_id}/tasks/{problem_id}"
    submit_url: "https://atcoder.jp/contests/{contest_id}/submit" 