# 言語設定
languages:
  rust:
    aliases:
      - Rust
      - rs
      - RUST
    extension: "rs"
    template:
      pattern:
        solution: "{source}.rs"
        generator: "{source}_gen.rs"
        tester: "{source}_test.rs"
      directory: "rust"
    site_ids:
      atcoder: "5054"  # Rust (rustc 1.70.0)
    runner:
      image: "rust:latest"
      compile: ["rustc", "main.rs"]
      run: ["./main"]
      compile_dir: "/compile/rust"
  
  pypy:
    aliases:
      - PyPy
      - py-py
      - PYPY
      - Pypy
      - py
    extension: "py"
    template:
      pattern:
        solution: "{source}.py"
        generator: "{source}_gen.py"
        tester: "{source}_test.py"
      directory: "python"
    site_ids:
      atcoder: "5078"  # Python (PyPy 3.10-v7.3.12)
    runner:
      image: "pypy:3.9-slim"
      compile: null
      run: ["pypy3", "-u", "-c"]
      compile_dir: "/compile/pypy"

  python:
    aliases:
      - Python
      - py
      - PYTHON
    extension: "py"
    template:
      pattern:
        solution: "{source}.py"
        generator: "{source}_gen.py"
        tester: "{source}_test.py"
      directory: "python"
    site_ids:
      atcoder: "5055"  # Python (CPython 3.11.4)
    runner:
      image: "python:3.9-slim"
      compile: null
      run: ["python", "-u", "-c"]
      compile_dir: "/compile/python"
  
  cpp:
    aliases:
      - C++
      - cpp
      - CPP
    extension: "cpp"
    template:
      pattern:
        solution: "{source}.cpp"
        generator: "{source}_gen.cpp"
        tester: "{source}_test.cpp"
      directory: "cpp"
    site_ids:
      atcoder: "5050"  # C++ (GCC 12.2.0)
    runner:
      image: "gcc:latest"
      compile: ["g++", "-std=c++17", "-O2", "main.cpp"]
      run: ["./a.out"]
      compile_dir: "/compile/cpp"