# Online Judge Tools の設定

# サブミット時の設定
submit:
  # サブミット後の待機時間（秒）
  # 0: 待機しない
  wait: 0
  
  # 確認プロンプトをスキップするか
  # true: 確認をスキップする
  # false: 確認プロンプトを表示する
  auto_yes: true

# テストケースの設定
test:
  # テストケースを保存するディレクトリ名
  # 問題ディレクトリからの相対パス
  directory: "test" 