[target.'cfg(all())']
rustflags = [
    "-D", "warnings",
    "-W", "clippy::all",
    "-W", "clippy::pedantic",
    "-W", "clippy::nursery",
    "-W", "clippy::disallowed_types",
    "-D", "clippy::unwrap_used",
    "-D", "clippy::result_large_err"
]

[alias]
check-all = "check --all-features --all-targets" 