timeout_seconds: 2
memory_limit_mb: 512
languages:
  python:
    image_name: "python:3.9-slim"
    run_cmd: ["python", "-u", "-c"]
    file_extension: "py"
    workspace_dir: "/workspace"
  cpp:
    image_name: "gcc:latest"
    compile_cmd: ["g++", "-std=c++17", "-O2", "-o", "/tmp/a.out"]
    run_cmd: ["/tmp/a.out"]
    file_extension: "cpp"
    workspace_dir: "/workspace"
  rust:
    image_name: "rust:latest"
    compile_cmd: ["rustc", "-O", "-o", "/tmp/a.out"]
    run_cmd: ["/tmp/a.out"]
    file_extension: "rs"
    workspace_dir: "/workspace" 