[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]

[[bin]]
name = "solution"
path = "src/solution.rs"

[[bin]]
name = "generator"
path = "src/generator.rs"

[[bin]]
name = "tester"
path = "src/tester.rs"
